import { default as RGBaseLayout } from './RGBaseLayout';
import { CalcNode, RelationGraphInstance, RGEventNames, RGForceLayoutOptions, RGNode, RGOptionsFull } from '../../types';
import { NodesAnalyticResult } from './analyzers/RGNetworkAnalyzer';
type CalcNode4Force = CalcNode & {
    Fx: number;
    Fy: number;
    dragging: boolean;
    force_weight: number;
    forceCenterOffset_X: number;
    forceCenterOffset_Y: number;
    fixed: boolean;
};
export declare class RGForceLayout extends RGBaseLayout {
    layoutOptions: RGForceLayoutOptions;
    private fastStart;
    private skipInitLayout;
    private maxLayoutTimes;
    private byNode;
    private byLine;
    private lockX;
    private lockY;
    private force_node_repulsion;
    private force_line_elastic;
    private disableLiveChanges;
    private force_x_coefficient;
    private force_y_coefficient;
    instanceId: string;
    constructor(layoutOptions: RGForceLayoutOptions, graphOptions: RGOptionsFull, graphInstance: RelationGraphInstance);
    updateOptions(layoutOptions: Partial<RGForceLayoutOptions>): void;
    calcNodes: RGNode[];
    placeNodes(calcNodes: RGNode[], rootNode?: RGNode): void;
    protected getLevelR(levelDistanceArr: number[], level: number): number | undefined;
    protected placeRelativePosition(rootNode: RGNode, groupNodes: RGNode[], analyticResult: NodesAnalyticResult, distanceCoefficient: number, levelDistanceArr: number[]): void;
    private calculateMinimumRadius;
    protected placeNodesInFanRegion(nodes: RGNode[], startDeg: number, endDeg: number, centerXy: {
        x: number;
        y: number;
    }, level: number, parentStrength: number, levelDistanceArr: number[], deep: number, distanceCoefficient: number, currentR: number): void;
    protected graphEventHandle(eventName: RGEventNames, ...args: any[]): void;
    protected _graphEventHandler: any;
    protected connectToGraphInstance(): void;
    protected disConnectToGraphInstance(): void;
    layoutTimes: number;
    prev10: number[];
    visibleNodes: RGNode[];
    updateVisibleNodes(allNode?: RGNode[]): void;
    protected viewUpdate(): void;
    autoLayout(forceLayout?: boolean): void;
    protected _onFinishCallback: () => void;
    onFinish(onFinishCallback: () => void): void;
    _onTickCallback: () => void;
    onTick(_onTickCallback: () => void): void;
    applyFBuffToNodes(): void;
    applyPositionToNodes(): void;
    protected layoutFinished(): void;
    protected resetCalcNodes(): void;
    protected calcNodeMap: WeakMap<RGNode, CalcNode4Force>;
    protected forCalcNodes: CalcNode4Force[];
    protected recentGraphVelocity: number[];
    protected graphVelocityBalancedValue: number;
    start(): void;
    doForceLayout(useTime: number): void;
    private prevLogTime;
    private animationFrameTimer;
    private prevNodeLevel1Index;
    private prevNodeLevel2Index;
    syncNodePosition(nodeId: string, x: number, y: number): void;
    calcNodesPosition(): false | undefined;
    private stoped;
    stop(): void;
    addElasticByLine(node1: CalcNode4Force, node2: CalcNode4Force, force_elastic?: number): void;
    maxTractionLength: number;
    zeroForceLength: number;
    maxRepulsionDistance: number;
    nodeCollisionRadius: number;
    maxMoveSpeed: number;
    n2nMaxForce: number;
    addGravityByNode(node1: CalcNode4Force, node2: CalcNode4Force, coefficient?: number): void;
    addFtoNode(node: CalcNode4Force, x: number, y: number): void;
    applyToNodePosition(node: CalcNode4Force): 0 | undefined;
}
export default RGForceLayout;
